### ISSUE TITLE
WrappableText with SelectableText widget

### ISSUE THREAD

**Issue by desmond206x** [ronjb/float_column#1]
We need to add a SelectableText widget to the WrappableText widget.
Currently it is impossible to make the text selectable.

Currently:
`WrappableText(
  text: TextSpan(children: [ ... ])
),`

Needed:
`WrappableText(
  text: SelectableText.rich(TextSpan(children: [ ... ]))
),`

https://api.flutter.dev/flutter/material/SelectableText/SelectableText.rich.html

**Comment by ronjb** [comment]
You're right, SelectableText cannot be used in WrappableText. However, I have a Selectable package that can be used to provide text selection over FloatColumn widgets. See: https://pub.dev/packages/selectable and for an example, look at: https://github.com/ronjb/selectable/blob/master/example/lib/main.dart.
