### ISSUE TITLE
Does it work with `SliverList`?

### ISSUE THREAD

**Issue by GCSBOSS** [ronjb/float_column#10]
Hello. I'm using a `SliverList` with a `SliverChildBuilderDelegate` to layout a _big_ list of paragraphs. Is there any way to make float_column work when my floated widget might be taller than a single paragraph (list item)?

**Comment by ronjb** [comment]
Hi @GCSBOSS,

Yes, it does work with SliverList. I've added a SliverList example to the example app so you can check out the code, and you can try it out here: https://ronjb.github.io/float_column (you may need to adjust the window width for best results).

As you can see, the height correctly adjusts to fit whichever is taller, the floated widget or text.

<img width="612" alt="Screenshot 2023-08-02 at 2 36 04 PM" src="https://github.com/ronjb/float_column/assets/1015193/eaf8bad1-24ca-4535-8ac8-75058a398ffa">

**Comment by GCSBOSS** [comment]
Nice!
The thing is kind need to emulate the web behavior where a single floated child may be sorrounded by flow content of even it's parent sibling blocks like this:

![image](https://github.com/ronjb/float_column/assets/11818414/4309ec13-b5eb-4256-83ab-11e49107b58a)

Not sure if I make much sense.

**Comment by ronjb** [comment]
The FloatColumn widget tries to emulate the web float behavior as best it can — within the constraints of the Flutter rendering system. All widgets, including FloatColumn are passed size constraints from the parent, and within those constraints they can determine their own size and the layout of their children, but that's it — a widget cannot tell its parent, its parent's siblings, etc. how to layout themselves. [Constraints go down. Sizes go up. Parent sets position.](https://docs.flutter.dev/ui/layout/constraints)

To achieve what you picture, the text blocks and floated widget would need to be contained in the same FloatColumn widget.

Hope that makes sense. Let me know if I'm misunderstanding something.

**Comment by GCSBOSS** [comment]
It makes complete sense. 

I wish I could hack this around somehow. It's kind of an important part of my layout.

I'm converting a Web App to Flutter for better performance and more seamless OS integration. Apparently I'm gonna stumble on those kind of issues. My App main feature involves formatting blocks of text in sligtly complex ways for display.

Let me know if you thnk this could be pulled of somehow even without your widget. Would be useful to hear someone experienced in Flutter about this.

Thanks a lot for you effort!

**Comment by ronjb** [comment]
It is possible — a great thing about Flutter is it is open source. I created FloatColumn for a reason similar to yours, I needed the functionality for a project I was working on. RenderFloatColumn is basically a merging of RenderFlex (the class that renders the Column widget) and RenderParagraph (the class that renders Text widgets). You could accomplish something similar by writing a "FloatSliverList" with "RenderFloatSliverList" by merging the functionality of RenderSliverMultiBoxAdaptor with RenderParagraph. :) Good luck!

**Comment by GCSBOSS** [comment]
Seems like I'll have a full month. Thank you so much for the pointers!
