### ISSUE TITLE
Incompatible with flutter 3.24.0

### ISSUE THREAD

**Issue by gibahjoe** [ronjb/float_column#12]
This library is incompatible with flutter 3.24.0

I get error `hosted/pub.dev/float_column-2.1.6/lib/src/selectable_fragment.dart(120,17): error G42E56F65: The type 'TextGranularity' is not exhaustively matched by the switch cases since it doesn't match 'TextGranularity.paragraph'.` when I try to build my app on windows. Seems `.paragraph` was added to TextGranularity

**Comment by ronjb** [comment]
just published a new version, 2.1.8, that fixes the problem
