### ISSUE TITLE
᲼

### ISSUE THREAD

**Issue by concrete92** [ronjb/float_column#2]

**Comment by ronjb** [comment]
@concrete92 You are right, FloatColumn can only wrap text from TextSpans (via the WrappableText data class). Like RichText, FloatColumn is a MultiChildRenderObjectWidget. It can’t wrap text that is already rendered, it needs to render the text to wrap it.

I took a look at the EasyRichText class, and it takes in `text` and a `patternList` and produces from that a list of TextSpans, which it then passes to either SelectableText.rich or RichText to render. It would be super easy to pull the code that parses the text and produces the list of TextSpans into a separate function, then the TextSpans could be used by FloatColumn to wrap the text around floated widgets.

Would you like to submit a pull request to github.com/2000calories/flutter_easy_rich_text to do this, or maybe I can find the time to do it this coming weekend.

Thanks for the comment by the way, and let me know if you have further questions.

**Comment by concrete92** [comment]
Hi, thank you for your reply. Although I'm not very fluent in Dart and Flutter, I tried to make a function that returns a `List<InlineSpan>` , from the source code of EasyRichText (normally returns a widget). I don't know if it is production ready or fully functional (url launcher does not work and I have the extension installed) but at least it can detect regex patterns, do text styling and it works inside WrappableText.

Here is the code: https://gist.github.com/concrete92/4e0758487508946db26b1f9e44d3676d

I'm open to suggestions. Thanks

**Comment by concrete92** [comment]
Solved, please delete this issue.
