### ISSUE TITLE
WrappableText maxline?

### ISSUE THREAD

**Issue by ChauCM** [ronjb/float_column#4]
is there a way to set max lines for WrappableText?

**Comment by ronjb** [comment]
There isn't currently. Should be fairly easy to add. I'll look into it when I have some time this weekend.

**Comment by ronjb** [comment]
@ChauCM,

I finally found some spare time to make the changes. In the latest float_column version (1.2.4), WrappableText has two new properties: `int? maxLines` and `TextOverflow overflow`. They behave just like they do for the Text and RichText widgets.

Let me know if you see any problems with the changes, or have any questions.
