### ISSUE TITLE
FlatColumn expands parent widget to max Size

### ISSUE THREAD

**Issue by mekhribonu-s-codexoptimus** [ronjb/float_column#6]
Here my widgets with just text
<img width="234" alt="image" src="https://user-images.githubusercontent.com/96077652/208642133-e20d0749-1d2f-402b-b3b3-87aa06928dd7.png">

Here are same widgets with FlatColumn inside. FlatColumn expands parent black widget to max width
<img width="236" alt="image" src="https://user-images.githubusercontent.com/96077652/208641941-fa2af41d-aaf8-4795-9f28-a7e0b7364b4b.png">

How I can solve this?

**Comment by ronjb** [comment]
In order for the FloatColumn renderer to know where to position floated widgets, it takes the maximum width of the constraints passed to it. If you're not floating widgets to the right or left for text to wrap around, there's no reason to use FloatColumn, just use the regular Column widget.

**Comment by ronjb** [comment]
@mekhri-codex,

If you have further questions, let me know. Otherwise I'm going to close this issue.

**Comment by ronjb** [comment]
Closing this issue because it's been inactive for a few months. Feel free to re-open if you have further questions.
