### ISSUE TITLE
how do you set the height of your image ?

### ISSUE THREAD

**Issue by NicTanghe** [ronjb/float_column#7]
It is unclear how you set the height at which an image appears.

I have played with all of the variables but it's position does not seem to change.
Only the text indents.

**Comment by ronjb** [comment]
FloatColumn, like the regular Column widget, lets the widgets it contains determine their own layout during the layout phase of rendering. So, for example, if you want an image widget to be a set size, the Image widget has width and height parameters that you can set to specific values.

**Comment by ronjb** [comment]
@NicTanghe,

I'm going to close this unless you have have further questions...

**Comment by ronjb** [comment]
Closing this issue because it's been inactive for a few months. Feel free to re-open if you have further questions.
